### ISSUE TITLE
Change DAL to make use of Promises and not Observables

### ISSUE THREAD

**Issue by mhornstein** [mhornstein/Glitters1#108]

**Comment by mhornstein** [comment]
As a result of the conversion, when login fails, the following error is presented. I guess that it is due to the mix of promises, observers and switchmap (tcp\websocket config).


(node:7248) UnhandledPromiseRejectionWarning: RequestError: Error: connect ECONNREFUSED 127.0.0.1:5005
    at new RequestError (C:\Users\morh1\Documents\FullStack\Glitters1\GlitterServer\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\morh1\Documents\FullStack\Glitters1\GlitterServer\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\morh1\Documents\FullStack\Glitters1\GlitterServer\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\morh1\Documents\FullStack\Glitters1\GlitterServer\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (C:\Users\morh1\Documents\FullStack\Glitters1\GlitterServer\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)

(node:7248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
